proxies:
  - name: 30DAY ID
    server: poe.garena.com
    port: 80
    type: vmess
    uuid: dd80a9db-c859-48f3-8b7b-6f87acbba0c9
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    servername: 
    network: ws
    ws-opts: 
      path: /worryfree
      headers: 
        Host: hostnic.bumiayu.biz.id
    udp: true
  - name: VMESS 7DAY
    server: poe.garena.com
    port: 80
    type: vmess
    uuid: ccaa5458-8564-4755-8d32-9c0522c10806
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    servername: 
    network: ws
    ws-opts: 
      path: /vmess
      headers: 
        Host: xray.josvpn.me
    udp: true
  - name: VLESS 7DAY
    server: poe.garena.com
    port: 80
    type: vless
    uuid: 1e078551-5b2c-4f22-a538-e56538f8da97
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: poe.garena.com
    network: ws
    ws-opts: 
      path: /vless
      headers: 
        Host: v2ray.josvpn.me
    udp: true
  - name: TROJAN 7DAY
    server: poe.garena.com
    port: 443
    type: trojan
    password: 6a20a4d6-fd64-4e21-a376-0112c2f93835
    skip-cert-verify: true
    sni: v2ray.josvpn.me
    network: ws
    ws-opts: 
      path: /trojan
      headers: 
        Host: v2ray.josvpn.me
    udp: true
  - name: SG GAME TLS
    server: poe.garena.com
    port: 443
    type: vless
    uuid: f69a85fe-4a6e-40f3-bcd0-f3c800388b58
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: sg.vlcfpages.my.id
    network: ws
    ws-opts: 
      path: /?ed=2048
      headers: 
        Host: sg.vlcfpages.my.id
    udp: true
  - name: SG VMESS
    server: poe.garena.com
    port: 80
    type: vmess
    uuid: c7a6a571-48b9-4667-9048-72e9359b1ca8
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    servername: 
    network: ws
    ws-opts: 
      path: /vmess
      headers: 
        Host: v2ray.josvpn.me
    udp: true
  - name: TROJAN
    server: poe.garena.com
    port: 443
    type: trojan
    password: geo
    skip-cert-verify: true
    sni: jamur.geotunnel.biz.id
    network: ws
    ws-opts: 
      path: /trojan
      headers: 
        Host: jamur.geotunnel.biz.id
    udp: true
  - name: ALIBABA
    server: poe.garena.com
    port: 80
    type: vless
    uuid: 6e6cb97e-57ac-4e8f-ad90-2b2fbb21bc45
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: poe.garena.com
    network: ws
    ws-opts: 
      path: /vless
      headers: 
        Host: alibaba.jam.mahal.filegear-sg.me
    udp: true
  - name: ID VLESS
    server: poe.garena.com
    port: 443
    type: vless
    uuid: 0bc51b14-02aa-40db-aeba-8a9569a7244d
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: id.vlcfpages.my.id
    network: ws
    ws-opts: 
      path: /?ed=2048
      headers: 
        Host: id.vlcfpages.my.id
    udp: true
  - name: SG TELE
    server: poe.garena.com
    port: 80
    type: vless
    uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: poe.garena.com
    network: ws
    ws-opts: 
      path: /vlesscf
      headers: 
        Host: sg.servless.us.to
    udp: true
  - name: GACOR
    server: poe.garena.com
    port: 80
    type: vmess
    uuid: c427d72b-d5fe-4ac6-84f1-211bf40d5fee
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    servername: 
    network: ws
    ws-opts: 
      path: /vmess
      headers: 
        Host: sg-latunnel.latunv.my.id
    udp: true
  - name: PutriVpn
    server: poe.garena.com
    port: 443
    type: trojan
    password: Putrivpn
    skip-cert-verify: true
    sni: sg-alibaba.putrivpn.xyz
    network: ws
    ws-opts: 
      path: /trojan
      headers: 
        Host: sg-alibaba.putrivpn.xyz
    udp: true
  - name: OPOK1
    server: ovo.id
    port: 443
    type: trojan
    password: Putrivpn
    skip-cert-verify: true
    sni: sg-4.tingkehvpn.filegear-sg.me
    network: ws
    ws-opts: 
      path: /trojan
      headers: 
        Host: sg-4.tingkehvpn.filegear-sg.me
    udp: true
  - name: OPOK2
    server: arjuna.axis.co.id
    port: 443
    type: trojan
    password: Putrivpn
    skip-cert-verify: true
    sni: sg-1.tingkehvpn.filegear-sg.me
    network: ws
    ws-opts: 
      path: /trojan
      headers: 
        Host: sg-1.tingkehvpn.filegear-sg.me
    udp: true
  - name: TELE
    server: poe.garena.com
    port: 443
    type: vmess
    uuid: 1052f24e-7b09-45eb-b0c5-d858eb124192
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: glweidf.cfd
    network: ws
    ws-opts: 
      path: /linkws
      headers: 
        Host: glweidf.cfd
    udp: true
