proxies:
  - name: 30DAY ID
    server: poe.garena.com
    port: 80
    type: vmess
    uuid: dd80a9db-c859-48f3-8b7b-6f87acbba0c9
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    servername: 
    network: ws
    ws-opts: 
      path: /worryfree
      headers: 
        Host: hostnic.bumiayu.biz.id
    udp: true
  - name: VMESS OPOK
    server: ovo.id
    port: 80
    type: vmess
    uuid: f090abaa-1bbe-4ebf-9190-c275931c2b54
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    servername: 
    network: ws
    ws-opts: 
      path: /vmess
      headers: 
        Host: aray.okgas.me
    udp: true
  - name: VLESS GAME
    server: poe.garena.com
    port: 80
    type: vless
    uuid: 4b35055a-c488-4e79-bb51-c47206e48afc
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: poe.garena.com
    network: ws
    ws-opts: 
      path: /vless
      headers: 
        Host: aray.okgas.me
    udp: true
  - name: TELE
    server: ovo.id
    port: 80
    type: vmess
    uuid: 1b6f10ef-f678-43f5-8fe5-9498a61a69d8
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    servername: 
    network: ws
    ws-opts: 
      path: /vmess
      headers: 
        Host: biz.caliphvpn.cloud
    udp: true
