proxies:
  - name: TRIAL
    server: poe.garena.com
    port: 80
    type: vless
    uuid: 3a694bdc-4f9c-471e-870b-66066fd669a6
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: poe.garena.com
    network: ws
    ws-opts: 
      path: /vless-ws
      headers: 
        Host: sg01.ipxray.xyz
    udp: true
  - name: VLESS SG
    server: poe.garena.com
    port: 80
    type: vless
    uuid: db85db67-cbaf-4792-9505-ee3316499a9f
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: ovo.id
    network: ws
    ws-opts: 
      path: /vless
      headers: 
        Host: v2ray.josvpn.me
    udp: true
  - name: CLOUDFRONT
    server: 18.161.49.87
    port: 80
    type: vless
    uuid: db85db67-cbaf-4792-9505-ee3316499a9f
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: ovo.id
    network: ws
    ws-opts: 
      path: /vless
      headers: 
        Host: v2ray.josvpn.me
    udp: true
  - name: TROJAN
    server: poe.garena.com
    port: 443
    type: trojan
    password: geo
    skip-cert-verify: true
    sni: jamur.geotunnel.biz.id
    network: ws
    ws-opts: 
      path: /trojan
      headers: 
        Host: jamur.geotunnel.biz.id
    udp: true
  - name: ALIBABA
    server: poe.garena.com
    port: 80
    type: vless
    uuid: 6e6cb97e-57ac-4e8f-ad90-2b2fbb21bc45
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: poe.garena.com
    network: ws
    ws-opts: 
      path: /vless
      headers: 
        Host: alibaba.jam.mahal.filegear-sg.me
    udp: true
