proxies:
  - name: VMESS 7DAY
    server: poe.garena.com
    port: 80
    type: vmess
    uuid: ccaa5458-8564-4755-8d32-9c0522c10806
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    servername: 
    network: ws
    ws-opts: 
      path: /vmess
      headers: 
        Host: xray.josvpn.me
    udp: true
  - name: VLESS 7DAY
    server: poe.garena.com
    port: 80
    type: vless
    uuid: 1e078551-5b2c-4f22-a538-e56538f8da97
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: poe.garena.com
    network: ws
    ws-opts: 
      path: /vless
      headers: 
        Host: v2ray.josvpn.me
    udp: true
  - name: TROJAN 7DAY
    server: poe.garena.com
    port: 443
    type: trojan
    password: 6a20a4d6-fd64-4e21-a376-0112c2f93835
    skip-cert-verify: true
    sni: v2ray.josvpn.me
    network: ws
    ws-opts: 
      path: /trojan
      headers: 
        Host: v2ray.josvpn.me
    udp: true
  - name: OPOK 3DAY
    server: ovo.id
    port: 80
    type: vmess
    uuid: bjhonstore-10k
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    servername: 
    network: ws
    ws-opts: 
      path: /vmess
      headers: 
        Host: atl1.bjhonstore.my.id
    udp: true
  - name: OPOK1 3DAY
    server: arjuna.axis.co.id
    port: 80
    type: vmess
    uuid: 1c3c90e4-a882-4dea-a386-43aef39025eb
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    servername: 
    udp: true
  - name: SG GAME TLS
    server: poe.garena.com
    port: 443
    type: vless
    uuid: f69a85fe-4a6e-40f3-bcd0-f3c800388b58
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: sg.vlcfpages.my.id
    network: ws
    ws-opts: 
      path: /?ed=2048
      headers: 
        Host: sg.vlcfpages.my.id
    udp: true
  - name: SG VMESS
    server: poe.garena.com
    port: 80
    type: vmess
    uuid: c7a6a571-48b9-4667-9048-72e9359b1ca8
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    servername: 
    network: ws
    ws-opts: 
      path: /vmess
      headers: 
        Host: v2ray.josvpn.me
    udp: true
  - name: SG VLESS
    server: poe.garena.com
    port: 80
    type: vless
    uuid: 05778680-f89b-4fc6-8858-480b4b29437f
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: poe.garena.com
    network: ws
    ws-opts: 
      path: /vless
      headers: 
        Host: xdo.josvpn.me
    udp: true
  - name: VLESS SG
    server: poe.garena.com
    port: 80
    type: vless
    uuid: db85db67-cbaf-4792-9505-ee3316499a9f
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername:
    network: ws
    ws-opts: 
      path: /vless
      headers: 
        Host: v2ray.josvpn.me
    udp: true
  - name: TROJAN
    server: poe.garena.com
    port: 443
    type: trojan
    password: geo
    skip-cert-verify: true
    sni: jamur.geotunnel.biz.id
    network: ws
    ws-opts: 
      path: /trojan
      headers: 
        Host: jamur.geotunnel.biz.id
    udp: true
  - name: ALIBABA
    server: poe.garena.com
    port: 80
    type: vless
    uuid: 6e6cb97e-57ac-4e8f-ad90-2b2fbb21bc45
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: poe.garena.com
    network: ws
    ws-opts: 
      path: /vless
      headers: 
        Host: alibaba.jam.mahal.filegear-sg.me
    udp: true
  - name: PREMIUM
    server: poe.garena.com
    port: 80
    type: vmess
    uuid: b9bd2879-fd12-4c38-8bbe-15c25268b716
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    servername: 
    network: ws
    ws-opts: 
      path: /vmess
      headers: 
        Host: shared.bhm.my.id
    udp: true
  - name: XRAY
    server: cdn.appslayer.com
    port: 80
    type: vmess
    uuid: b5c54aee-29e0-4d4b-9bab-dfa89b59ba07
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    servername: 
    network: ws
    ws-opts: 
      path: /vmess
      headers: 
        Host: xdo.josvpn.me
    udp: true
  - name: TRIAL
    server: cdn.appslyer.com
    port: 80
    type: vless
    uuid: 2fe26d40-a24f-4677-91a7-50e109b6ec01
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: cdn.appslyer.com
    network: ws
    ws-opts: 
      path: /vless-ws
      headers: 
        Host: sg01.ipxray.xyz
    udp: true
